apiVersion: v1
kind: Service
metadata:
  name: = #{common.fullName}

  #[merge]{common.labels}
  labels: {}

  #[merge]{common.annotations}
  annotations: {}

#[merge]{service.spec}
spec:
  type: LoadBalancer #{service.type}

  #[merge]{common.labels}
  selector: {}

  ports:

    #[repeat]{ports}
    - port: 0 #{it.exposedPort or it.port}
      name: = #{i}
      targetPort: = #{i}
      nodePort: 0 #[if]{config.nodePort}
