kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: = #{common.fullName}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: = #{common.fullName}

subjects:
  - kind: ServiceAccount
    name: = #{common.fullName}
    namespace: default #{common.namespace}
